### PR TITLE
update cli.md

### LINKED ISSUE #135: Update Docs to CLI v0.1.3-alpha
Subspace CLI v0.1.3-alpha came out today, we need to update the documentation to this version. 

To update the version simply go into the cli page `CTRL + F` search `v0.1.2-alpha` and replace all with `v0.1.3-alpha`

### PR DESCRIPTION
**Pull request by AnimeshKumar923**
closes #135 
review requested @achiurizo @ImmaZoni

### CODE REVIEW

**Comment by AnimeshKumar923** [comment]
Didn't update the download links to the release binary files as v.0.1.3 download files are not available. On clicking the download button, v0.1.2 is downloaded.

What should be done about it?

**Comment by achiurizo** [comment]
@AnimeshKumar923 thanks for the contributions!

> Didn't update the download links to the release binary files as v.0.1.3 download files are not available

We have [v0.1.3](https://github.com/subspace/subspace-cli/releases/tag/v0.1.3-alpha) released so I think we can go ahead and link in this PR if you want to add it here 🙌

**Comment by AnimeshKumar923** [comment]
@achiurizo I've made the required changes. Please review it and provide necessary feedback.
Actually, I couldn't find the download link to the files. Thank you for providing that.

**Comment by achiurizo** [comment]
> @achiurizo I've made the required changes. Please review it and provide necessary feedback. Actually, I'm little bit new here (in Open-Source world) and couldn't find the download link to the files. Thank you for providing that.

No worries, and you are doing great @AnimeshKumar923. Thanks for the contributions again and welcome to open source! 🚀

**Comment by AnimeshKumar923** [comment]
> > @achiurizo I've made the required changes. Please review it and provide necessary feedback. Actually, I'm little bit new here (in Open-Source world) and couldn't find the download link to the files. Thank you for providing that.
> 
> No worries, and you are doing great @AnimeshKumar923. Thanks for the contributions again and welcome to open source! 🚀 

Thank you! 🙇

**Comment by AnimeshKumar923** [comment]
Feels nice when the PR is merged. Satisfaction and inner peace😌 @achiurizo

**Pull request merged**
