### PR TITLE
Fix some broken links

### PR DESCRIPTION
**Pull request by jim-counter**
Fix broken links discovered during macOS testing.

### CODE REVIEW

**Comment by EmilFattakhov** [comment]
Do you think we should set up the redirect from the space-acres to space-acres-recommended @jim-counter?

**Comment by jim-counter** [comment]
> Do you think we should set up the redirect from the space-acres to space-acres-recommended @jim-counter?

Sounds like a good idea. Can you add it to this PR?

**Comment by EmilFattakhov** [comment]
Added

**Comment by EmilFattakhov** [comment]
The last commit not broken link per-se, but fits into fixing broken stuff pr.

**Pull request merged**
