### PR TITLE
Update security.md

### PR DESCRIPTION
**Pull request by mathematicw**
structure improved;
many corrections are made to improve readability and grammar.

### CODE REVIEW

**Comment by mathematicw** [comment]
Sorry for complicating the review by breaking the diff. But there are still a lot of changes here. 
Though of course, I can do a PR update ...

**Review by EmilFattakhov — APPROVED** [review]
Looks good @mathematicw, appreciate your contribution!
I'll merge this PR later this week and resolve all the conflicts as soon as a larger [refactoring PR](https://github.com/subspace/subspace-docs/pull/319) is merged, there is nothing else you need to do. 

Keep the PRs coming, we're loving it!

**Comment by mathematicw** [comment]
Emil says, we should do like this

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by mathematicw** [comment]
> Text wrapped in code blocks seems quite hard to read to me.

in "Upgrading.." ?

**Comment by EmilFattakhov** [comment]
Thank you for bearing with me @mathematicw!
I merged your changes with the most recent changes for out documentation and made a few styling improvements to make things more readable. 
Please let me know if you are happy with the changes and if yes, I can merge them!

Will do the same with your other PR 😉

**Pull request merged**
