### PR TITLE
Add `notification.yml` & updates `test.yml`

### PR DESCRIPTION
**Pull request by ImmaZoni**
### Introduction 🌟
This PR introduces two new GitHub Actions that aim to automate our testing and community notification processes when there are version changes in Pulsar and Advanced CLI. Below, you'll find detailed explanations of the functional logic embedded in these workflows.

#### How the Version Check Works
1. **Fetching Differences**:  
   - The `git diff main...HEAD` command compares the main branch with the latest commit for specific `.mdx` files.
   - The differences are stored in `pulsar_diff.txt` and `substrate_cli_diff.txt`.

2. **Parsing for Version Changes**:  
   - Using `grep` and `awk`, the script extracts the new and old version tags from the diff files.
   - If there's a version change, it is dynamically added to the PR body.

#### How the Notification Trigger Works
1. **Version Tag Comparison**:  
   - Similar to `test.yml`, this action also uses `git diff`, `grep`, and `awk` to extract new and old version tags.
   - The extracted tags are stored in environment variables.

2. **Fetching Release Notes**:  
   - If new version tags are detected, the action fetches the release notes from GitHub using a REST API call.
  
3. **Discord Notification**:  
   - Based on the detected changes, a Discord message is constructed.
   - The message includes new version tags and fetched release notes.
   - It uses conditional logic to customize the message based on which software has been updated: Pulsar, Advanced CLI, or both.

### Example Scenarios 📝
1. **Scenario 1**:  
   - You update Pulsar from `v0.0.1` to `v0.0.2`.
   - `test.yml` updates the PR body with a checkbox and a warning for the change.
   - the `test.yml` will fail until this checkbox is checked and acknowledged. 
   - Upon merging, `notification.yml` sends a Discord message with details of the new version and its release notes.

2. **Scenario 2**:  
   - You make a PR with no version changes.
   - `test.yml` will not make any changes to the PR body.
   - `notification.yml` will not send any Discord message upon merging.

### Conclusion 
These GitHub Actions are designed to keep our community informed about version changes in Pulsar and Advanced CLI, ensuring transparency and engagement. Your reviews and feedback are much appreciated!

### CODE REVIEW

**Review by jim-counter — COMMENTED** [review]
Looks good to me. Have you tested it?

**Review by EmilFattakhov — APPROVED** [review]
This looks awesome Justin, I had no idea that Github Workflows support this kind of actions, smart solution! 
Code-wise everything looks great and reasonable, I'm not sure how to test this though. I think we should be fine even if something will not be working as intended, as it won't break anything!

**Review by jim-counter — COMMENTED** [review]
Is there anywhere I can see the output of a test run @ImmaZoni?

**Comment by ImmaZoni** [comment]
Hey @jim-counter and @EmilFattakhov firstly, sorry for absolutely blowing up your GitHub inbox with all these various tests and updates. 

Ive got this to a point where I am pretty confident it will work. I have updated the test section to do the following
1. Upon detection of a version change, the PR Body will have a warning/acknowledgement added. This will be a check box that is unchecked. 
2. The test will fail as long as this checkbox is unchecked. 
3. Upon checking of the checkbox, the edit of the PR Body re-triggers the workflow to run and verify that the checkbox is checked. (ensuring the maintainer realizes they are about to notify the community)


I have tested this side of the action very extensively and its working smoothly, I have also gone through the notification workflow multiple times to ensure it is ready to go, unfortunately that part we cannot test until its time

_PS: Sorry for the horrific commit history, tried a squash but ran it backwards by mistake🤦_

**Comment by EmilFattakhov** [comment]
No worries about the notifications Justin!

I've looked at the output on [PR 236](https://github.com/subspace/subspace-docs/pull/236) it looks great!

**Review by jim-counter — APPROVED** [review]
No worries about the notifications @ImmaZoni! I have been here myself. LGTM!

**Pull request merged**
