### PR TITLE
Integrate Algolia Search into Subspace Documentation

### PR DESCRIPTION
**Pull request by ImmaZoni**
### Introduction

This pull request introduces Algolia Search as a new feature in the Subspace documentation, marking the first time a search functionality has been implemented to enhance the accessibility and user experience of the documentation site.

### Objectives

- To provide immediate, relevant search results to users navigating the Subspace documentation.
- To lay the foundation for scalable, powerful search capabilities as the documentation grows.

### Implementation Overview

Algolia was selected for its excellence in search performance, user-friendly integration, and comprehensive analytics. This initial implementation includes:

- Configuring Algolia to index the Subspace documentation content.
- Embedding the Algolia search bar and results display into the documentation site's layout.
- Tailoring the search experience to match the needs and expectations of the Subspace community.

### Algolia Account and Management

An Algolia account has been set up for the purpose of this feature implementation. I am prepared to hand over control of this account to the Subspace team, ensuring a seamless transition and continuous management of the search functionality.

### Key Benefits

- **Enhanced User Experience:** Users can now quickly find the information they need, improving their learning and troubleshooting experience.
- **Scalability:** Algolia provides a robust platform that can grow with the Subspace documentation, accommodating future expansions seamlessly.
- **Analytics Insights:** The Algolia dashboard offers valuable insights into search patterns, which can be used to further improve the documentation.

### CODE REVIEW

**Comment by EmilFattakhov** [comment]
Hope you don't mind me pushing the required node version directly at your PR 😉, it's just faster to check if it compiles this way.

**Comment by EmilFattakhov** [comment]
@ImmaZoni I believe the indexing might have not been done yet, please try performing a search and check the logs. I can help debug if you share the algolia credentials with me :)

**Comment by ImmaZoni** [comment]
Hey @EmilFattakhov! From my understanding of the Algolia docs i don't think it will index until it hits production. I will send you a Discord DM with the credentials for Algolia so we can take a look 🙏

**Review by EmilFattakhov — APPROVED** [review]
I think you're right in the assumption that we need to merge it to production first Justin, giving this a try and re-open the PR in case something is missing. Thank you so much for your PR @ImmaZoni, and hope to see more PRs from you!

**Pull request merged**
