### PR TITLE
Visual C++ Redistributable Note

### PR DESCRIPTION
**Pull request by ryyeung**

### CODE REVIEW

**Review by EmilFattakhov — CHANGES_REQUESTED** [review]
Thanks for picking this up Ryan!
The link that you linked presumes that you're on Windows, could you please split this  message into three <option> tabs and link the guide to install the C++ Redistributable for each of the systems separately? 
If you don't like the idea of tabs, you can expand on a message and link three different guides for each system inside of it. Thanks!

**Comment by ryyeung** [comment]
Hey @EmilFattakhov, this is what I found for the Linux and Mac pkgs, not sure if we want to link these.

Linux:
https://askubuntu.com/questions/1440508/running-aplications-that-require-the-c-redistributable-for-visual-studio-2015

Mac:
https://stackoverflow.com/questions/54578618/i-am-using-mac-can-i-install-visual-c-2015-redistribution-because-after-that

**Comment by EmilFattakhov** [comment]
Sorry @ryyeung, forgot to get back to you on Friday. 
On MacOS C++ Redistributable comes as a part of the [Visual Studio](https://visualstudio.microsoft.com/vs/mac/) so let's link this instead.
For Linux, we can link [this instruction](https://learn.microsoft.com/en-us/cpp/linux/download-install-and-setup-the-linux-development-workload?view=msvc-170#linux-setup-ubuntu-on-wsl)

**Comment by ryyeung** [comment]
@EmilFattakhov @randywessels Added Linux and Mac Notes to PR

**Comment by EmilFattakhov** [comment]
@ryyeung FYU made some small adjustments (merged three warnings into one) before merging!

**Pull request merged**
